baseURL = "https://hypedrivendev.io/"
languageCode = "en-us"
title = "Hype Driven Dev"
theme = "hugo-journal"
publishDir = "docs"

[author]
  name = "Cédric Exbrayat"
[params]
  description = "Hype Driven Development"
  githubUsername = "cexbrayat"
  twitterUsername = "cedric_exbrayat"
  tagline = "Because we love new stuff."
[params.work]
  jobTitle = "Co-founder and developer"
  company = "Ninja Squad"
  companyUrl = "https://ninja-squad.com/"
[params.ebook]
  name = "Become a ninja with Angular"
  url = "https://books.ninja-squad.com/angular"
[params.conference]
  name = "MiXiT"
  url = "https://mixitconf.org"
